# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a750ef4c2a4dd9f9cc6b72b9a013ef67bd7456180decbe0b166c409495d93bf99f594ed2f604f779ae8916199d32100c18896daa46f1dc1d60b43ffb106d17e7

test:
  secret_key_base: b318c04291642bb8daa086e82c8a2252fbcd48e15ed139d64186184e24ad12520453c3edce680528deb29ac5ca4a3fab9bfafd8e3cddd5a55ea67451d75518ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
